{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter",
    "version": "2.3.3.RELEASE",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6",
      "buildId": "tg4hme55tfa5hnl6wmusorolwu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "2.3.3.RELEASE"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "2.3.3.RELEASE"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-logging",
          "version": {
            "requires": "2.3.3.RELEASE"
          }
        },
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "1.3.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.2.8.RELEASE"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.26"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-2.3.3.RELEASE.jar",
          "url": "spring-boot-starter-2.3.3.RELEASE.jar",
          "size": 4762,
          "sha512": "9c05cd37b08b95c16744c48473f6bda115656ea5bf8663aae0d34337b2084d3c6daa925769baf4703c7f9b9089cb8758b92b97b501964603a58e5366b7ab2ebc",
          "sha256": "be19878791765c8aaff208465edd45c12292b10739f425beb1612d2fa50145ee",
          "sha1": "c9bb3464e83990465b86fb94da3d20f92f036d1e",
          "md5": "dd1db9b502fd93399a05a588d110e373"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "2.3.3.RELEASE"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "2.3.3.RELEASE"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-logging",
          "version": {
            "requires": "2.3.3.RELEASE"
          }
        },
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "1.3.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.2.8.RELEASE"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.26"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-2.3.3.RELEASE.jar",
          "url": "spring-boot-starter-2.3.3.RELEASE.jar",
          "size": 4762,
          "sha512": "9c05cd37b08b95c16744c48473f6bda115656ea5bf8663aae0d34337b2084d3c6daa925769baf4703c7f9b9089cb8758b92b97b501964603a58e5366b7ab2ebc",
          "sha256": "be19878791765c8aaff208465edd45c12292b10739f425beb1612d2fa50145ee",
          "sha1": "c9bb3464e83990465b86fb94da3d20f92f036d1e",
          "md5": "dd1db9b502fd93399a05a588d110e373"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-2.3.3.RELEASE-javadoc.jar",
          "url": "spring-boot-starter-2.3.3.RELEASE-javadoc.jar",
          "size": 4762,
          "sha512": "9c05cd37b08b95c16744c48473f6bda115656ea5bf8663aae0d34337b2084d3c6daa925769baf4703c7f9b9089cb8758b92b97b501964603a58e5366b7ab2ebc",
          "sha256": "be19878791765c8aaff208465edd45c12292b10739f425beb1612d2fa50145ee",
          "sha1": "c9bb3464e83990465b86fb94da3d20f92f036d1e",
          "md5": "dd1db9b502fd93399a05a588d110e373"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-2.3.3.RELEASE-sources.jar",
          "url": "spring-boot-starter-2.3.3.RELEASE-sources.jar",
          "size": 4762,
          "sha512": "9e80ab3e2bfc5c67182f334dac6c83d56e900d5b94d2c7c348b3951ea33ae465bf18237f42f25701c5f0f1a200e511db33637d23153935c0d88347600a87edb6",
          "sha256": "3f91a882782e36bea88f1d233dca482b01cac4252cbae8da529f6a50b0270095",
          "sha1": "d462e49471f51a74a3be5846bd1a7af1ecee8c1c",
          "md5": "67adad9de92b38ef5eac84477a986c30"
        }
      ]
    }
  ]
}
