{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-tomcat",
    "version": "2.3.3.RELEASE",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6",
      "buildId": "tg4hme55tfa5hnl6wmusorolwu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "1.3.5"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-core",
          "version": {
            "requires": "9.0.37"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        },
        {
          "group": "org.glassfish",
          "module": "jakarta.el",
          "version": {
            "requires": "3.0.3"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-websocket",
          "version": {
            "requires": "9.0.37"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-tomcat-2.3.3.RELEASE.jar",
          "url": "spring-boot-starter-tomcat-2.3.3.RELEASE.jar",
          "size": 4789,
          "sha512": "b5cec59b0bc70969481d216bb44b535e3c6163d51d9255c2a4411f4eb832606df80b159b56b4045ce02bf4000b2b68cac32a5a2527a8cf35b578f1b877fd6741",
          "sha256": "8333f472a9a9e0e075e72ddb6084e0b32e2294b2fc386e50de0ecd1b68a561f2",
          "sha1": "542a0aaf0f584d186d9bd052ab10a5cf357a5b39",
          "md5": "10b15934c487c45ea1235bbb9ab490e6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "1.3.5"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-core",
          "version": {
            "requires": "9.0.37"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        },
        {
          "group": "org.glassfish",
          "module": "jakarta.el",
          "version": {
            "requires": "3.0.3"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-websocket",
          "version": {
            "requires": "9.0.37"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-tomcat-2.3.3.RELEASE.jar",
          "url": "spring-boot-starter-tomcat-2.3.3.RELEASE.jar",
          "size": 4789,
          "sha512": "b5cec59b0bc70969481d216bb44b535e3c6163d51d9255c2a4411f4eb832606df80b159b56b4045ce02bf4000b2b68cac32a5a2527a8cf35b578f1b877fd6741",
          "sha256": "8333f472a9a9e0e075e72ddb6084e0b32e2294b2fc386e50de0ecd1b68a561f2",
          "sha1": "542a0aaf0f584d186d9bd052ab10a5cf357a5b39",
          "md5": "10b15934c487c45ea1235bbb9ab490e6"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-tomcat-2.3.3.RELEASE-javadoc.jar",
          "url": "spring-boot-starter-tomcat-2.3.3.RELEASE-javadoc.jar",
          "size": 4789,
          "sha512": "b5cec59b0bc70969481d216bb44b535e3c6163d51d9255c2a4411f4eb832606df80b159b56b4045ce02bf4000b2b68cac32a5a2527a8cf35b578f1b877fd6741",
          "sha256": "8333f472a9a9e0e075e72ddb6084e0b32e2294b2fc386e50de0ecd1b68a561f2",
          "sha1": "542a0aaf0f584d186d9bd052ab10a5cf357a5b39",
          "md5": "10b15934c487c45ea1235bbb9ab490e6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-tomcat-2.3.3.RELEASE-sources.jar",
          "url": "spring-boot-starter-tomcat-2.3.3.RELEASE-sources.jar",
          "size": 4789,
          "sha512": "b5cec59b0bc70969481d216bb44b535e3c6163d51d9255c2a4411f4eb832606df80b159b56b4045ce02bf4000b2b68cac32a5a2527a8cf35b578f1b877fd6741",
          "sha256": "8333f472a9a9e0e075e72ddb6084e0b32e2294b2fc386e50de0ecd1b68a561f2",
          "sha1": "542a0aaf0f584d186d9bd052ab10a5cf357a5b39",
          "md5": "10b15934c487c45ea1235bbb9ab490e6"
        }
      ]
    }
  ]
}
